services:
  backend:
    build:
      context: ./backend
    container_name: cloud-log-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/sample-logs:/app/sample-logs

  frontend:
    build:
      context: ./frontend
    container_name: cloud-log-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
